const tagsDataSource: any = [
  {
    key: 1,
    name: 'FirstName',
    gg: null,
    npc0: `%FirstName:Npc:1%`,
    npc1: `%FirstName:Npc:2%`,
    npc2: `%FirstName:Npc:3%`,
  },
  {
    key: 2,
    name: 'FullName',
    gg: null,
    npc0: `%FullName:Npc:1%`,
    npc1: `%FullName:Npc:2%`,
    npc2: `%FullName:Npc:3%`,
  },
  {
    key: 3,
    name: 'He/She',
    gg: `%He/She:0%`,
    npc0: `%He/She:1%`,
    npc1: `%He/She:2%`,
    npc2: `%He/She:3%`,
  },
  {
    key: 4,
    name: 'Him/Her',
    gg: `%Him/Her:0%`,
    npc0: `%Him/Her:1%`,
    npc1: `%Him/Her:2%`,
    npc2: `%Him/Her:3%`,
  },
  {
    key: 5,
    name: 'His/Her',
    gg: `%His/Her:0%`,
    npc0: `%His/Her:1%`,
    npc1: `%His/Her:2%`,
    npc2: `%His/Her:3%`,
  },
  {
    key: 6,
    name: 'His/Hers',
    gg: `%His/Hers:0%`,
    npc0: `%His/Hers:1%`,
    npc1: `%His/Hers:2%`,
    npc2: `%His/Hers:3%`,
  },
  {
    key: 7,
    name: 'Himself/Herself',
    gg: `%Himself/Herself:0%`,
    npc0: `%Himself/Herself:1%`,
    npc1: `%Himself/Herself:2%`,
    npc2: `%Himself/Herself:3%`,
  },
  {
    key: 8,
    name: 'Contact name',
    gg: null,
    npc0: `%Class:1%`,
    npc1: `%Class:2%`,
    npc2: `%Class:3%`,
  },
  {
    key: 9,
    name: 'Mr./Ms.',
    gg: `%MrMs:0%`,
    npc0: `%MrMs:1%`,
    npc1: `%MrMs:2%`,
    npc2: `%MrMs:3%`,
  },
  {
    key: 10,
    name: 'LastName',
    gg: `%LastName:0%`,
    npc0: `%LastName:1%`,
    npc1: `%LastName:2%`,
    npc2: `%LastName:3%`,
  },
];

export default tagsDataSource;
